id: f7c0b4e7ce9c4e898bc06cb9b764f011
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_211-Teaching_the_Fundamental_Exposition_of_Dependent_Arising-v2
  language: en
  author: ''
  volume: {}
